version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/auth-services"
    schedule:
      interval: "daily"
  
    assignees:
      - "efiaroca"
    
    commit-message:
      prefix: "[aroca-fault]"

    labels:
      - "aroca-fault"
      - "pip"
      - "damn"
      - "dependencies"